### ISSUE TITLE
The same for browsers?

### ISSUE THREAD

**Issue by kuraga** [bahmutov/pre-compiled#2]
@bahmutov thanks for your work!

Is there some trick to get the same for browsers?

Thanks.

**Comment by bahmutov** [comment]
So for browsers it is a little trickier. I have made https://github.com/bahmutov/babel-service but this is limited to the browsers that support ServiceWorkers. One could really transpile for Node 5 and then use it on the browsers - major browsers support the features supported by Node 5 by this point
